### ISSUE TITLE
Url is not defined when running with serverless-offline

### ISSUE THREAD

**Issue by JefStat** [supercharge/hapi-aws-lambda#12]
Adding a test with serverless offline results in the following error

```
    "url" [1]: ""
  }

  [1] "url" is not allowed to be empty
✖ ValidationError: {
```
```yml
service: sls-test

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev

plugins:
  - serverless-offline

functions:
  app:
    handler: examples/hapi-serverless/lambda.handler
    memorySize: 384 # default is 1024 MB
    events:
      - http: ANY /
```
1. run `serverless-offline`
2. open in browser http://localhost:3000/dev
